// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UsersAPI.Models;

#nullable disable

namespace UsersAPI.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UsersAPI.Models.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevokedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Guid");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("4635728d-b2ed-47f9-b5b9-b73220a1ca67"),
                            Admin = true,
                            Birthday = new DateTime(2022, 4, 30, 20, 52, 5, 180, DateTimeKind.Local).AddTicks(4390),
                            CreatedBy = "Init",
                            Gender = 1,
                            Login = "Admin",
                            Name = "Admin",
                            Password = "secret123"
                        },
                        new
                        {
                            Guid = new Guid("a97c1ca4-7d0b-445f-83b1-7f81d19c9845"),
                            Admin = false,
                            Birthday = new DateTime(1979, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Init",
                            Gender = 0,
                            Login = "User1",
                            Name = "User1",
                            Password = "secret123"
                        },
                        new
                        {
                            Guid = new Guid("da2158b3-cabc-4a7c-b887-449364f9ed3d"),
                            Admin = false,
                            Birthday = new DateTime(1999, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Init",
                            Gender = 0,
                            Login = "User2",
                            Name = "User2",
                            Password = "secret123"
                        },
                        new
                        {
                            Guid = new Guid("2a4202c9-15ee-4c79-97cc-5719c81ebc98"),
                            Admin = false,
                            Birthday = new DateTime(2004, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Init",
                            Gender = 0,
                            Login = "User3",
                            Name = "User3",
                            Password = "secret123"
                        },
                        new
                        {
                            Guid = new Guid("1c7ebad1-90c2-4111-81b7-9368149c415a"),
                            Admin = false,
                            Birthday = new DateTime(2003, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Init",
                            Gender = 1,
                            Login = "User4",
                            Name = "User4",
                            Password = "secret123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
